POST http://localhost:3000/logout
Content-Type: application/json
x-client-id: 100437
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMDA0MzcsInVzZXJuYW1lIjoiamFrZXB0bm4yNTVAZ21haWwuY29tIiwiaWF0IjoxNzMyODA0MjQxLCJleHAiOjE3MzI4MTE0NDF9.Hhq_vy-z302UvYJUCNFIYHBPTB6kSAni9wRR5y0FkNI
x-rf-token-id: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMDA0MzcsInVzZXJuYW1lIjoiamFrZXB0bm4yNTVAZ21haWwuY29tIiwiaWF0IjoxNzMyODA0MjQxLCJleHAiOjE3MzM0MDkwNDF9.WcdUL-87xnOyNcYgj0izaIrPHqdyz2J8bOtDDm9oK2I

