POST http://localhost:3000/register
#Content-Type: application/json

#{
#  "username": "exampleUser",
#  "email": "user@example.com",
#  "password": "examplePassword",
#  "confirm_password": "examplePassword"
#}
#
